name: 'Algorithm question generator'
description: 'Greet someone and record the time'
inputs:
  json-data:  # id of input
    description: 'Reading the json file'
    required: true
    default: 'data.json'
  github-token:
    description: "github token"
    required: true
runs:
  using: 'node12'
  main: 'index.js'