on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      uses: muchirijane/Algorithm-questions-generator@master
      with:
        data-path: 'data.json'
    # Use the output from the `hello` step
